/*
 * Created on 10 Aug 2016 ( Time 19:50:10 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.crewguru.business.service;

import java.util.List;

import com.crewguru.bean.Location;

/**
 * Business Service Interface for entity Location.
 */
public interface LocationService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Location findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Location> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Location save(Location entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Location update(Location entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Location create(Location entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
