/*
 * Created on 10 Aug 2016 ( Time 19:50:10 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.crewguru.business.service;

import java.util.List;

import com.crewguru.bean.WorkExperience;

/**
 * Business Service Interface for entity WorkExperience.
 */
public interface WorkExperienceService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	WorkExperience findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<WorkExperience> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	WorkExperience save(WorkExperience entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	WorkExperience update(WorkExperience entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	WorkExperience create(WorkExperience entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
