/*
 * Created on 10 Aug 2016 ( Time 19:50:10 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.crewguru.business.service;

import java.util.List;

import com.crewguru.bean.WorkCategory;

/**
 * Business Service Interface for entity WorkCategory.
 */
public interface WorkCategoryService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	WorkCategory findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<WorkCategory> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	WorkCategory save(WorkCategory entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	WorkCategory update(WorkCategory entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	WorkCategory create(WorkCategory entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
