/*
 * Created on 10 Aug 2016 ( Time 19:50:10 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.crewguru.business.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import com.crewguru.bean.Location;
import com.crewguru.bean.jpa.LocationEntity;
import com.crewguru.business.service.LocationService;
import com.crewguru.business.service.mapping.LocationServiceMapper;
import com.crewguru.data.repository.jpa.LocationJpaRepository;

/**
 * Implementation of LocationService
 */
@Component
@Transactional
public class LocationServiceImpl implements LocationService {

	@Resource
	private LocationJpaRepository locationJpaRepository;

	@Resource
	private LocationServiceMapper locationServiceMapper;
	
	@Override
	public Location findById(Integer id) {
		LocationEntity locationEntity = locationJpaRepository.findOne(id);
		return locationServiceMapper.mapLocationEntityToLocation(locationEntity);
	}

	@Override
	public List<Location> findAll() {
		Iterable<LocationEntity> entities = locationJpaRepository.findAll();
		List<Location> beans = new ArrayList<Location>();
		for(LocationEntity locationEntity : entities) {
			beans.add(locationServiceMapper.mapLocationEntityToLocation(locationEntity));
		}
		return beans;
	}

	@Override
	public Location save(Location location) {
		return update(location) ;
	}

	@Override
	public Location create(Location location) {
		LocationEntity locationEntity = locationJpaRepository.findOne(location.getId());
		if( locationEntity != null ) {
			throw new IllegalStateException("already.exists");
		}
		locationEntity = new LocationEntity();
		locationServiceMapper.mapLocationToLocationEntity(location, locationEntity);
		LocationEntity locationEntitySaved = locationJpaRepository.save(locationEntity);
		return locationServiceMapper.mapLocationEntityToLocation(locationEntitySaved);
	}

	@Override
	public Location update(Location location) {
		LocationEntity locationEntity = locationJpaRepository.findOne(location.getId());
		locationServiceMapper.mapLocationToLocationEntity(location, locationEntity);
		LocationEntity locationEntitySaved = locationJpaRepository.save(locationEntity);
		return locationServiceMapper.mapLocationEntityToLocation(locationEntitySaved);
	}

	@Override
	public void delete(Integer id) {
		locationJpaRepository.delete(id);
	}

	public LocationJpaRepository getLocationJpaRepository() {
		return locationJpaRepository;
	}

	public void setLocationJpaRepository(LocationJpaRepository locationJpaRepository) {
		this.locationJpaRepository = locationJpaRepository;
	}

	public LocationServiceMapper getLocationServiceMapper() {
		return locationServiceMapper;
	}

	public void setLocationServiceMapper(LocationServiceMapper locationServiceMapper) {
		this.locationServiceMapper = locationServiceMapper;
	}

}
