/*
 * Created on 3 Sep 2016 ( Time 06:22:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.crewguru.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "WORK_EXPERIENCE"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="WORK_EXPERIENCE", catalog="crewguru" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="WorkExperienceEntity.countAll", query="SELECT COUNT(x) FROM WorkExperienceEntity x" )
} )
public class WorkExperienceEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="Company", length=50)
    private String     company      ;

    @Column(name="Description", length=1000)
    private String     description  ;

    @Column(name="JobTitle", length=100)
    private String     jobtitle     ;

    @Temporal(TemporalType.DATE)
    @Column(name="from_date")
    private Date       fromDate     ;

    @Temporal(TemporalType.DATE)
    @Column(name="to_date")
    private Date       toDate       ;

    @Column(name="workdates", length=25)
    private String     workdates    ;

	// "userId" (column "user_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="user_id", referencedColumnName="user_id")
    private UserEntity user        ;



    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public WorkExperienceEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : Company ( VARCHAR ) 
    public void setCompany( String company ) {
        this.company = company;
    }
    public String getCompany() {
        return this.company;
    }

    //--- DATABASE MAPPING : Description ( VARCHAR ) 
    public void setDescription( String description ) {
        this.description = description;
    }
    public String getDescription() {
        return this.description;
    }

    //--- DATABASE MAPPING : JobTitle ( VARCHAR ) 
    public void setJobtitle( String jobtitle ) {
        this.jobtitle = jobtitle;
    }
    public String getJobtitle() {
        return this.jobtitle;
    }

    //--- DATABASE MAPPING : from_date ( DATE ) 
    public void setFromDate( Date fromDate ) {
        this.fromDate = fromDate;
    }
    public Date getFromDate() {
        return this.fromDate;
    }

    //--- DATABASE MAPPING : to_date ( DATE ) 
    public void setToDate( Date toDate ) {
        this.toDate = toDate;
    }
    public Date getToDate() {
        return this.toDate;
    }

    //--- DATABASE MAPPING : workdates ( VARCHAR ) 
    public void setWorkdates( String workdates ) {
        this.workdates = workdates;
    }
    public String getWorkdates() {
        return this.workdates;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setUser( UserEntity user ) {
        this.user = user;
    }
    public UserEntity getUser() {
        return this.user;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(company);
        sb.append("|");
        sb.append(description);
        sb.append("|");
        sb.append(jobtitle);
        sb.append("|");
        sb.append(fromDate);
        sb.append("|");
        sb.append(toDate);
        sb.append("|");
        sb.append(workdates);
        return sb.toString(); 
    } 

}
