/*
 * Created on 10 Aug 2016 ( Time 19:50:10 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.crewguru.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;

import com.crewguru.bean.Industry;
import com.crewguru.bean.jpa.IndustryEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class IndustryServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public IndustryServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'IndustryEntity' to 'Industry'
	 * @param industryEntity
	 */
	public Industry mapIndustryEntityToIndustry(IndustryEntity industryEntity) {
		if(industryEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Industry industry = map(industryEntity, Industry.class);

		return industry;
	}
	
	/**
	 * Mapping from 'Industry' to 'IndustryEntity'
	 * @param industry
	 * @param industryEntity
	 */
	public void mapIndustryToIndustryEntity(Industry industry, IndustryEntity industryEntity) {
		if(industry == null) {
			return;
		}

		//--- Generic mapping 
		map(industry, industryEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}