/*
 * Created on 10 Aug 2016 ( Time 19:50:10 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.crewguru.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;

import com.crewguru.bean.WorkCategory;
import com.crewguru.bean.jpa.WorkCategoryEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class WorkCategoryServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public WorkCategoryServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'WorkCategoryEntity' to 'WorkCategory'
	 * @param workCategoryEntity
	 */
	public WorkCategory mapWorkCategoryEntityToWorkCategory(WorkCategoryEntity workCategoryEntity) {
		if(workCategoryEntity == null) {
			return null;
		}

		//--- Generic mapping 
		WorkCategory workCategory = map(workCategoryEntity, WorkCategory.class);

		return workCategory;
	}
	
	/**
	 * Mapping from 'WorkCategory' to 'WorkCategoryEntity'
	 * @param workCategory
	 * @param workCategoryEntity
	 */
	public void mapWorkCategoryToWorkCategoryEntity(WorkCategory workCategory, WorkCategoryEntity workCategoryEntity) {
		if(workCategory == null) {
			return;
		}

		//--- Generic mapping 
		map(workCategory, workCategoryEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}