/*
 * Created on 11 Aug 2016 ( Time 20:28:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.crewguru.bean;

import java.io.Serializable;
import java.math.BigInteger;

import javax.validation.constraints.*;

import java.util.Date;

public class UserProfile implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 50 )
    private String userId;

    @NotNull
    @Size( min = 1, max = 500 )
    private String profession;

    @Size( max = 1000 )
    private String profileImage;
    
    @Size( max = 1000 )
    private String backgroundImage;

    @NotNull
    @Size( min = 1, max = 500 )
    private String profilename;

    @NotNull
    @Size( min = 1, max = 4000 )
    private String profiledescription;

    @NotNull
    private Date createdDate;

    @NotNull
    private Date updatedDate;

    @Size( max = 500 )
    private String twitterLink;

    @Size( max = 500 )
    private String facebookLink;

    @Size( max = 500 )
    private String instagramLink;

    @Size( max = 500 )
    private String linkedinLink;

    @Size( max = 3000 )
    private String aboutMe;


    private Boolean availabilityHire;

    @Size( max = 150 )
    private String website;

    @Size( max = 2000 )
    private String skills;


    private BigInteger phonenumber;


    private Integer phoneext;
    
    @Size( max = 500 )
    private String industry;
    
    @Size( max = 500 )
    private String workCategory;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    
    
    public void setUserId( String userId ) {
        this.userId = userId;
    }
    public String getIndustry() {
		return industry;
	}

	public void setIndustry(String industry) {
		this.industry = industry;
	}

	public String getWorkCategory() {
		return workCategory;
	}

	public void setWorkCategory(String workCategory) {
		this.workCategory = workCategory;
	}

	public String getUserId() {
        return this.userId;
    }

    public void setProfession( String profession ) {
        this.profession = profession;
    }
    public String getProfession() {
        return this.profession;
    }

    public void setProfileImage( String profileImage ) {
        this.profileImage = profileImage;
    }
    public String getProfileImage() {
        return this.profileImage;
    }

    
    
    public String getBackgroundImage() {
		return backgroundImage;
	}

	public void setBackgroundImage(String backgroundImage) {
		this.backgroundImage = backgroundImage;
	}

	public void setProfilename( String profilename ) {
        this.profilename = profilename;
    }
    public String getProfilename() {
        return this.profilename;
    }

    public void setProfiledescription( String profiledescription ) {
        this.profiledescription = profiledescription;
    }
    public String getProfiledescription() {
        return this.profiledescription;
    }

    public void setCreatedDate( Date createdDate ) {
        this.createdDate = createdDate;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setUpdatedDate( Date updatedDate ) {
        this.updatedDate = updatedDate;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }

    public void setTwitterLink( String twitterLink ) {
        this.twitterLink = twitterLink;
    }
    public String getTwitterLink() {
        return this.twitterLink;
    }

    public void setFacebookLink( String facebookLink ) {
        this.facebookLink = facebookLink;
    }
    public String getFacebookLink() {
        return this.facebookLink;
    }

    public void setInstagramLink( String instagramLink ) {
        this.instagramLink = instagramLink;
    }
    public String getInstagramLink() {
        return this.instagramLink;
    }

    public void setLinkedinLink( String linkedinLink ) {
        this.linkedinLink = linkedinLink;
    }
    public String getLinkedinLink() {
        return this.linkedinLink;
    }

    public void setAboutMe( String aboutMe ) {
        this.aboutMe = aboutMe;
    }
    public String getAboutMe() {
        return this.aboutMe;
    }

    public void setAvailabilityHire( Boolean availabilityHire ) {
        this.availabilityHire = availabilityHire;
    }
    public Boolean getAvailabilityHire() {
        return this.availabilityHire;
    }

    public void setWebsite( String website ) {
        this.website = website;
    }
    public String getWebsite() {
        return this.website;
    }

    public void setSkills( String skills ) {
        this.skills = skills;
    }
    public String getSkills() {
        return this.skills;
    }

    public void setPhonenumber( BigInteger phonenumber ) {
        this.phonenumber = phonenumber;
    }
    public BigInteger getPhonenumber() {
        return this.phonenumber;
    }

    public void setPhoneext( Integer phoneext ) {
        this.phoneext = phoneext;
    }
    public Integer getPhoneext() {
        return this.phoneext;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(userId);
        sb.append("|");
        sb.append(profession);
        sb.append("|");
        sb.append(profileImage);
        sb.append("|");
        sb.append(backgroundImage);
        sb.append("|");
        sb.append(profilename);
        sb.append("|");
        sb.append(profiledescription);
        sb.append("|");
        sb.append(createdDate);
        sb.append("|");
        sb.append(updatedDate);
        sb.append("|");
        sb.append(twitterLink);
        sb.append("|");
        sb.append(facebookLink);
        sb.append("|");
        sb.append(instagramLink);
        sb.append("|");
        sb.append(linkedinLink);
        sb.append("|");
        sb.append(aboutMe);
        sb.append("|");
        sb.append(availabilityHire);
        sb.append("|");
        sb.append(website);
        sb.append("|");
        sb.append(skills);
        sb.append("|");
        sb.append(id);
        sb.append("|");
        sb.append(phonenumber);
        sb.append("|");
        sb.append(phoneext);
        return sb.toString(); 
    } 


}
