/*
 * Created on 10 Aug 2016 ( Time 20:43:40 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.crewguru.bean;

import java.io.Serializable;
import java.util.List;

import javax.persistence.OneToMany;
import javax.validation.constraints.*;

import com.crewguru.bean.jpa.LocationEntity;

import com.crewguru.bean.jpa.UserProfileEntity;
import com.crewguru.bean.jpa.UserProjectsEntity;

import com.crewguru.bean.jpa.WorkExperienceEntity;


public class User implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 50 )
    private String userId;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 15 )
    private String password;

    @Size( max = 50 )
    private String firstname;

    @Size( max = 50 )
    private String lastname;

    @NotNull
    @Size( min = 1, max = 100 )
    private String emailId;


   
   
   
    private List<UserProjects> listOfUserProjects;

    
    private List<UserProfile> listOfUserProfile;

   
    private List<WorkExperience> listOfWorkExperience;

    
    private List<Location> listOfLocation;

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setUserId( String userId ) {
        this.userId = userId ;
    }

    public String getUserId() {
        return this.userId;
    }


    
    
    
	

	public List<UserProjects> getListOfUserProjects() {
		return listOfUserProjects;
	}

	public void setListOfUserProjects(List<UserProjects> listOfUserProjects) {
		this.listOfUserProjects = listOfUserProjects;
	}

	public List<UserProfile> getListOfUserProfile() {
		return listOfUserProfile;
	}

	public void setListOfUserProfile(List<UserProfile> listOfUserProfile) {
		this.listOfUserProfile = listOfUserProfile;
	}

	public List<WorkExperience> getListOfWorkExperience() {
		return listOfWorkExperience;
	}

	public void setListOfWorkExperience(List<WorkExperience> listOfWorkExperience) {
		this.listOfWorkExperience = listOfWorkExperience;
	}

	public List<Location> getListOfLocation() {
		return listOfLocation;
	}

	public void setListOfLocation(List<Location> listOfLocation) {
		this.listOfLocation = listOfLocation;
	}

	//----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setPassword( String password ) {
        this.password = password;
    }
    public String getPassword() {
        return this.password;
    }

    public void setFirstname( String firstname ) {
        this.firstname = firstname;
    }
    public String getFirstname() {
        return this.firstname;
    }

    public void setLastname( String lastname ) {
        this.lastname = lastname;
    }
    public String getLastname() {
        return this.lastname;
    }

    public void setEmailId( String emailId ) {
        this.emailId = emailId;
    }
    public String getEmailId() {
        return this.emailId;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(userId);
        sb.append("|");
        sb.append(password);
        sb.append("|");
        sb.append(firstname);
        sb.append("|");
        sb.append(lastname);
        sb.append("|");
        sb.append(emailId);
        return sb.toString(); 
    } 


}
