/*
 * Created on 3 Sep 2016 ( Time 06:22:25 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.crewguru.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class WorkExperience implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 50 )
    private String userId;

    @Size( max = 50 )
    private String company;

    @Size( max = 1000 )
    private String description;

    @Size( max = 100 )
    private String jobtitle;


    private Date fromDate;


    private Date toDate;

    @Size( max = 25 )
    private String workdates;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setUserId( String userId ) {
        this.userId = userId;
    }
    public String getUserId() {
        return this.userId;
    }

    public void setCompany( String company ) {
        this.company = company;
    }
    public String getCompany() {
        return this.company;
    }

    public void setDescription( String description ) {
        this.description = description;
    }
    public String getDescription() {
        return this.description;
    }

    public void setJobtitle( String jobtitle ) {
        this.jobtitle = jobtitle;
    }
    public String getJobtitle() {
        return this.jobtitle;
    }

    public void setFromDate( Date fromDate ) {
        this.fromDate = fromDate;
    }
    public Date getFromDate() {
        return this.fromDate;
    }

    public void setToDate( Date toDate ) {
        this.toDate = toDate;
    }
    public Date getToDate() {
        return this.toDate;
    }

    public void setWorkdates( String workdates ) {
        this.workdates = workdates;
    }
    public String getWorkdates() {
        return this.workdates;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(userId);
        sb.append("|");
        sb.append(company);
        sb.append("|");
        sb.append(description);
        sb.append("|");
        sb.append(jobtitle);
        sb.append("|");
        sb.append(fromDate);
        sb.append("|");
        sb.append(toDate);
        sb.append("|");
        sb.append(workdates);
        return sb.toString(); 
    } 


}
